const $=id=>document.getElementById(id);let rows=[];let stationCatalog={};if(localStorage.getItem("weather-atlas-theme")==="dark")document.body.classList.add("dark");
const num=(v,d=1)=>v==null?"—":Number(v).toFixed(d);
function stationId(){const value=$("station").value.trim();const match=Object.entries(stationCatalog).find(([,station])=>station.name===value);return match?match[0]:value}
async function loadStations(){stationCatalog=await (await fetch("/api/stations")).json();$("station-list").innerHTML=Object.values(stationCatalog).sort((a,b)=>a.name.localeCompare(b.name)).map(station=>`<option value="${station.name}"></option>`).join("")}
async function load(){const start=+$("start").value,end=+$("end").value;if(start<1980||end<start){$("status").textContent="Choose a valid year range.";return} $("status").textContent="Loading annual observations…";try{const r=await fetch(`/api/analysis?station=${encodeURIComponent(stationId())}&start=${start}-01-01&end=${end}-12-31`);if(!r.ok)throw Error();const p=await r.json();rows=p.data;render(p.station);$("status").textContent=`${rows.length} annual records · Meteostat observations loaded`}catch(e){$("status").textContent="Could not load annual Meteostat analysis."}}
function render(station){if(!rows.length)return;const first=rows.slice(0,5),last=rows.slice(-5),mean=a=>a.reduce((s,r)=>s+r.avg_temp,0)/a.length,signal=mean(last)-mean(first),hot=rows.reduce((a,b)=>b.avg_temp>a.avg_temp?b:a),wet=rows.reduce((a,b)=>b.rainfall>a.rainfall?b:a);$("signal").textContent=(signal>=0?"+":"")+num(signal)+"°";$("warmest").textContent=hot.year;$("warmestValue").textContent=`${num(hot.avg_temp)}°C average`;$("wettest").textContent=wet.year;$("wettestValue").textContent=`${num(wet.rainfall,0)} mm`;$("count").textContent=rows.length;$("rangeLabel").textContent=`${rows[0].year} — ${rows.at(-1).year} · ${station.name}`;draw();table()}
function draw(){const s=$("chart"),W=1000,H=360,p={l:42,r:20,t:22,b:42},max=Math.max(...rows.map(r=>Math.abs(r.anomaly)),1),x=i=>p.l+i/(rows.length-1||1)*(W-p.l-p.r),y=v=>p.t+(max-v)/(max*2)*(H-p.t-p.b),zero=y(0);let o=`<line class="gridline" x1="${p.l}" x2="${W-p.r}" y1="${zero}" y2="${zero}"/><text class="axis" x="0" y="${zero+4}">0°</text>`;rows.forEach((r,i)=>{const bw=Math.max(2,(W-p.l-p.r)/rows.length-3),yy=y(Math.max(r.anomaly,0)),h=Math.abs(y(r.anomaly)-zero);o+=`<rect x="${x(i)-bw/2}" y="${r.anomaly>=0?yy:zero}" width="${bw}" height="${h}" rx="2" fill="${r.anomaly>=0?'#f06d38':'#3d9bc2'}" opacity=".8"/><title>${r.year}: ${r.anomaly>=0?'+':''}${num(r.anomaly)}°C</title>`});[0,.25,.5,.75,1].forEach(t=>{const i=Math.min(rows.length-1,Math.floor(t*(rows.length-1)));o+=`<text class="axis" text-anchor="${t?'middle':'start'}" x="${x(i)}" y="${H-10}">${rows[i].year}</text>`});s.innerHTML=o}
function table(){const sorted=[...rows].sort((a,b)=>$("sort").value==="year"?a.year-b.year:b[$("sort").value]-a[$("sort").value]);$("table").innerHTML=sorted.map(r=>`<tr><td><b>${r.year}</b></td><td>${num(r.avg_temp)}°C</td><td class="${r.anomaly>=0?'positive':'negative'}">${r.anomaly>=0?'+':''}${num(r.anomaly)}°</td><td>${num(r.rainfall,0)} mm</td><td>${r.wet_days}</td><td>${num(r.avg_wind)} km/h</td><td>${num(r.coldest)}° / ${num(r.warmest)}°</td></tr>`).join("")}
$("load").onclick=load;$("station").onchange=load;$("sort").onchange=table;$("themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("weather-atlas-theme",document.body.classList.contains("dark")?"dark":"light")};loadStations().then(load);
